apiVersion: batch/v1
kind: CronJob
metadata:
  name: parking-ingest-cron
spec:
  schedule: "0 * * * *" # Every hour on the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: spark-k8s-sa
          containers:
          - name: ingestor
            image: us-central1-docker.pkg.dev/ladot-496020/parking-repo/parking-ingest:v1
            env:
            - name: BUCKET_NAME
              value: "parking-data-lake-v1"
          restartPolicy: OnFailure
