FROM apache/spark-py:v3.4.0

USER root

ENV ICEBERG_VERSION=1.3.1
ENV SPARK_VERSION=3.4_2.12
ENV GCS_CONNECTOR_VERSION=hadoop3-2.2.14

ADD https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${SPARK_VERSION}/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_VERSION}-${ICEBERG_VERSION}.jar /opt/spark/jars/
ADD https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/${GCS_CONNECTOR_VERSION}/gcs-connector-${GCS_CONNECTOR_VERSION}-shaded.jar /opt/spark/jars/
RUN chmod 644 /opt/spark/jars/iceberg-spark-runtime*.jar /opt/spark/jars/gcs-connector*.jar

WORKDIR /app
RUN chown -R 185:0 /app

COPY --chown=185:0 data_pipeline/processing/process_parking.py data_pipeline/processing/process_inventory.py data_pipeline/ingestion/ingest_parking.py data_pipeline/ingestion/ingest_inventory.py data_pipeline/processing/validate_tables.py ./

USER 185

CMD ["/opt/spark/bin/spark-submit", "/app/process_parking.py"]
