FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data_pipeline/ingestion/ingest_parking.py data_pipeline/ingestion/ingest_inventory.py ./

CMD ["python", "ingest_parking.py"]
