apiVersion: batch/v1
kind: Job
metadata:
  name: parking-process-job
spec:
  template:
    spec:
      serviceAccountName: spark-k8s-sa
      containers:
      - name: processor
        image: us-central1-docker.pkg.dev/ladot-496020/parking-repo/parking-processor:v1
        imagePullPolicy: Always
        args: ["/opt/spark/bin/spark-submit", "/app/process_parking.py"]
        env:
        - name: BUCKET_NAME
          value: "parking-data-lake-v1"
      restartPolicy: Never
